sudo: required
dist: trusty
addons:
  apt:
    packages:
      - ruby-dev
language: c
compiler:
  - gcc
  - clang
script:
  - rake test
os:
  - linux
  - osx
services:
  - postgresql
addons:
  homebrew:
    packages:
    - postgresql